version: "3.9"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopify_orders
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    volumes:
      - ./frontend:/app

volumes:
  mysql-data:
